version: '3.8'

services:
  vue-app:
    build:
      context: .  # The path to your project with the Dockerfile
    ports:
      - "8080:80"  # Map port 80 inside the container to port 8080 on the host
    restart: always  # Automatically restart the container if it crashes
    volumes:
      - ./dist:/usr/share/nginx/html  # Sync dist folder with Nginx's HTML directory
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Use custom Nginx configuration
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
